export const myCourses = [
  /* programming */
  {id:'1' ,
	CourseName:"Flutter",
	comingSoon: false,
	InstructorName: "Omar Abdelaziz",
	InstructorTitle:"Flutter Developer",
	InstructorImage:"./images/omar.png",
	InstructorDetails1:"Expertise: 3 years of experience in designing, developing, and maintaining mobile applications",
	InstructorDetails2:"Creative, Instant",
	InstructorDetails3:"Enthusiastic and detail-oriented Flutter Developer with three years of experience in designing, developing, and maintaining mobile applications. Proven expertise in creating high-quality, scalable, and efficient applications using Flutter and Dart. Adept at working in fast-paced environments and collaborating with cross-functional teams to deliver innovative solutions.",

	content:[
 	"•  Dart Basics"	,
	"•	Object-Oriented Programming (OOP)",
	"•	Asynchronous Programming",
	"•	Introduction to Flutter",
	"•	Widgets",
	"•	Navigation and Routing",
	"•	State Management",
	"•	Working with APIs",
	"•	Animations",
	"•	Database Integration",
	"•	Design Patterns",
	"•	Advanced Topics",
  ] ,
  duration: "4 Months",
	Details :"Launch your Flutter journey and build stunning apps " ,
	category :["cs"] , 
	imgPath:"./images/flutter2.png", 
	// price: '5000',             
	discountedPrice: '5000 '   
	
},
  {id:'2' ,CourseName:"React" ,comingSoon: true, InstructorName: "Ahmed",
		InstructorTitle:"Flutter Developer",
	// InstructorImage:"./images/omar.png",
	InstructorDetails1:"Expertise: 3 years of experience in designing developing, and maintaining mobile applications",
	InstructorDetails2:"Creative, Instant",
	InstructorDetails3:"Enthusiastic and detail-oriented Flutter Developer with three years of experience in designing, developing, and maintaining mobile applications. Proven expertise in creating high-quality, scalable, and efficient applications using Flutter and Dart. Adept at working in fast-paced environments and collaborating with cross-functional teams to deliver innovative solutions.",
Details :"Build Real Web Apps with React"  ,category :["cs"], imgPath:"./images/React2.webp"},
  {id:'3' ,CourseName:"Data Science",comingSoon: true, InstructorName: "Someone" ,Details :"Gain in-demand data science skills and build professional applications " ,category :["cs"] , imgPath:"./images/d2.png"},
 
  /* Art */
  {id:'4' ,CourseName:"Digital Painting",
	comingSoon: false, 
	InstructorName: "Dai Ashraf" , 
	InstructorTitle:"Instructor in ITI",
	InstructorImage:"./images/Dai.png",
	InstructorDetails1:"Game Artist in Golden Eagle Tech" ,
	content:[
	"• Drawing Fundamentals:"	,
	   "--> Fundamentals of Digital Painting"	,
	   "--> Basic drawing skills",
	   "--> Line quality",
	   "-->	Color theory",
	   "-->	Basic objects",
	   "-->	Lighting and shading",
	   "-->	Steps to build your scene with colors",
	   "-->	Texturing concepts and techniques",
	   "-->	Seamless And tileable textures",
	   "",
	"•	How to use Photoshop for drawing:",
	   "-->	Photoshop tools uses in digital painting",
	   "-->	Steps and layers arrangements",
	   "--> Shapes and Forms & Light and Shadows",
	   "-->	Line quality and Values",
	   "-->	Steps to make environment thumbnails",
	   "-->	Depth, perspective types",
	 ] ,
	 duration: "6 weeks (1.5 Month)",
	 	// price: '5000',             
	discountedPrice: '2000 ' ,
	Details :"Edit like a pro, design like a creator — even if you are just starting " ,category :["art"] , imgPath:"./images/photoshop2.png"},
  {id:'5' ,CourseName:"Blender 3D Model",comingSoon: true, InstructorName: "Ahmed Abosaeda" ,Details :"create your own 3D models, render stunning scenes, and build a portfolio that stands out",category :["art"] , imgPath:"./images/blender.jpg"},
  {id:'6' ,CourseName:"Modeling Using Maya",comingSoon: true, InstructorName: "Hajar" ,Details :"create high-quality 3D assets for games, film, and animation " ,category :["art"] , imgPath:"./images/Maya.png"},

]